name: Build OnePlus kernel modules

permissions:
  contents: write
  actions: write

inputs:
  op_config_json:
    required: true
    type: string
  manifest:
    required: true
    type: string
    default: OOS15

runs:
  using: composite
  steps:
    - name: ðŸš€ Cleanup
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get clean

    - name: ðŸ› ï¸ Install Essential Tools
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          bc bison build-essential flex git-core libelf-dev libssl-dev \
          unzip jq python3 rsync ccache

    - name: ðŸ“¥ Sync Source (Verified Branch)
      shell: bash
      run: |
        set -euo pipefail
        # Ember ki branch ka folder structure
        CONFIG="OP10pro"
        echo "CONFIG=$CONFIG" >> "$GITHUB_ENV"
        
        REPO="/usr/local/bin/repo"
        [ ! -x "$REPO" ] && curl -s https://storage.googleapis.com/git-repo-downloads/repo -o "$REPO" && chmod +x "$REPO"
        
        mkdir -p "$CONFIG" && cd "$CONFIG"
        # Using the exact manifest Ember provided for OP10
        "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8450 -m oneplus_10_pro_v.xml --depth=1
        "$REPO" sync -c -j$(nproc --all) --no-clone-bundle --no-tags

    - name: ðŸ’‰ Inject RTL8188EU & NetHunter Fixes
      shell: bash
      run: |
        cd "OP10pro/kernel_platform/msm-kernel"
        # Adding the driver Ember recommended
        git clone --depth=1 https://github.com/ivanovborislav/rtl8188eu.git drivers/net/wireless/rtl8188eu
        echo "obj-m += rtl8188eu/" >> drivers/net/wireless/Makefile
        
        # NetHunter Configs
        cat >> arch/arm64/configs/gki_defconfig <<EOF
        CONFIG_MODULES=y
        CONFIG_RTL8188EU=m
        CONFIG_TCP_CONG_BBR=y
        CONFIG_NETFILTER_XT_TARGET_TTL=m
        CONFIG_IP_SET=m
        CONFIG_FRAME_WARN=0
        EOF

    - name: ðŸ—ï¸ Build Phase (The Final Lap)
      shell: bash
      run: |
        cd "$GITHUB_WORKSPACE/OP10pro/kernel_platform/msm-kernel"
        
        # Run 28 Success Patches
        sed -i '1i #include <linux/mm.h>' drivers/thermal/thermal_sysfs.c
        find . -name kgdb.h -exec sed -i 's/asm ("brk %0"/\/\/ asm ("brk %0"/' {} +
        sed -i 's/scan_adjusted =/bool scan_adjusted =/' mm/vmscan.c
        
        # Finding Clang Compiler in the synced source
        CLANG_PATH=$(find $GITHUB_WORKSPACE/OP10pro/kernel_platform -name clang -type f -path "*/bin/clang" | head -n 1 | xargs dirname)
        export PATH="$CLANG_PATH:$PATH"
        
        OUT=out
        make ARCH=arm64 O=$OUT LLVM=1 mrproper
        
        # Ember's Advice: Merge Waipio GKI config
        ./scripts/kconfig/merge_config.sh -O $OUT -m arch/arm64/configs/gki_defconfig arch/arm64/configs/vendor/waipio_GKI.config
        
        # Disable LTO to prevent storage/RAM crash
        ./scripts/config --file "$OUT/.config" --disable CONFIG_LTO_CLANG_THIN --disable CONFIG_LTO_CLANG_FULL
        
        # Compilation with Master Flags to ignore broken Oplus code
        make -j$(nproc --all) ARCH=arm64 LLVM=1 O=$OUT \
            KCFLAGS="-Wno-error -Wno-macro-redefined -Wno-declaration-after-statement" \
            modules
        
        mkdir -p artifacts
        find $OUT -name "*.ko" -exec cp {} artifacts/ \;
        cd artifacts && zip -r ../kernel_modules_final.zip .

    - name: ðŸ“¤ Upload
      uses: actions/upload-artifact@v4
      with:
        name: jinn-modules-final
        path: OP10pro/kernel_platform/msm-kernel/kernel_modules_final.zip
        
