name: Build OnePlus kernel modules (Final Fix)

permissions:
  contents: write
  actions: write

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true
    type: string
  optimize_level:
    required: false
    type: string
    default: O2
  manifest:
    required: true
    type: string
    default: OOS15

runs:
  using: composite
  steps:
    - name: Parse op_config_json
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"

    - name: Set Manifest
      shell: bash
      run: |
        set -euo pipefail
        echo "OP_MANIFEST=$OP_MANIFEST_${{ inputs.manifest }}_MODULES" >> "$GITHUB_ENV"

    - name: Install Minimal Dependencies
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get -o Acquire::Retries=3 update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          git curl ca-certificates build-essential clang lld flex bison \
          libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool \
          libxml2-utils rsync unzip dwarves file python3 ccache
        sudo apt-get clean

    - name: Setup Base Environment
      shell: bash
      run: |
        set -euo pipefail
        CONFIG="$OP_MODEL"
        echo "CONFIG=$CONFIG" >> "$GITHUB_ENV"
        REPO="/usr/local/bin/repo"
        if [ ! -x "$REPO" ]; then
          curl -s https://storage.googleapis.com/git-repo-downloads/repo -o "$REPO"
          chmod +x "$REPO"
        fi
        echo "REPO=$REPO" >> "$GITHUB_ENV"

    - name: Initialize and Sync Kernel Source
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$CONFIG"
        cd "$CONFIG"
        if [[ "$OP_MANIFEST" == https://* ]]; then
          mkdir -p .repo/manifests
          curl --fail --show-error --location --proto '=https' "$OP_MANIFEST" -o .repo/manifests/temp_manifest.xml
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m temp_manifest.xml --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        else
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b "$OP_BRANCH" -m "$OP_MANIFEST" --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        fi
        
        success=false
        for i in 1 2 3; do
          if "$REPO" sync -c --no-clone-bundle --no-tags --optimized-fetch -j"$(nproc --all)" --fail-fast; then
            success=true
            break
          fi
          sleep 30
        done
        $success || { echo "repo sync failed"; exit 1; }

    - name: Get Kernel Version Info
      shell: bash
      run: |
        set -euo pipefail
        CONFIG_DIR="$GITHUB_WORKSPACE/$CONFIG"
        ARTIFACTS_DIR="$CONFIG_DIR/artifacts"
        mkdir -p "$ARTIFACTS_DIR"
        cd "$CONFIG_DIR/kernel_platform/msm-kernel"
        VERSION=$(grep '^VERSION *=' Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep '^PATCHLEVEL *=' Makefile | awk '{print $3}')
        echo "KERNEL_VER=$VERSION.$PATCHLEVEL" >> "$GITHUB_ENV"
        echo "KERNEL_FULL_VER=$VERSION.$PATCHLEVEL-Modules" >> "$GITHUB_ENV"

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.19
      with:
        key: ${{ env.CONFIG }}-modules-${{ env.KERNEL_FULL_VER }}
        max-size: 5G

    - name: 🛠️ Fix Compiler Errors (The Triple Fix)
      shell: bash
      run: |
        set -euo pipefail
        MSM_DIR="$GITHUB_WORKSPACE/$CONFIG/kernel_platform/msm-kernel"
        
        # 1. Thermal Sysfs Fix (Missing Header)
        THERMAL_FILE="$MSM_DIR/drivers/thermal/thermal_sysfs.c"
        if [ -f "$THERMAL_FILE" ]; then
             sed -i '1i #include <linux/mm.h>' "$THERMAL_FILE"
             echo "✅ Fixed thermal_sysfs.c"
        fi

        # 2. Stack Pointer Fix (Clang Error)
        SP_FILE="$MSM_DIR/arch/arm64/include/asm/stack_pointer.h"
        if [ -f "$SP_FILE" ]; then
             sed -i 's/register unsigned long current_stack_pointer asm ("sp");/unsigned long current_stack_pointer = 0;/' "$SP_FILE"
             echo "✅ Fixed stack_pointer.h"
        fi

        # 3. KGDB Fix (Assembler Error)
        KGDB_FILE="$MSM_DIR/arch/arm64/include/asm/kgdb.h"
        if [ -f "$KGDB_FILE" ]; then
             sed -i 's/asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/\/\/ asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/' "$KGDB_FILE"
             echo "✅ Fixed kgdb.h"
        fi

    - name: Configure NetHunter Drivers
      shell: bash
      run: |
        set -euo pipefail
        KERNEL_PATH="$GITHUB_WORKSPACE/$CONFIG/kernel_platform"
        MSM="$KERNEL_PATH/msm-kernel"
        cd "$MSM"
        cat >> arch/arm64/configs/gki_defconfig <<EOF
        CONFIG_WLAN_VENDOR_REALTEK=y
        CONFIG_RTL8188EU=m
        CONFIG_R8188EU=m
        CONFIG_WLAN_VENDOR_ATH=y
        CONFIG_ATH9K=m
        CONFIG_ATH9K_HTC=m
        CONFIG_WLAN_VENDOR_MEDIATEK=y
        CONFIG_MT7601U=m
        CONFIG_MT76_USB=m
        EOF

    - name: Add rtw88 modules (Source Code)
      shell: bash
      run: |
        set -euo pipefail
        KERNEL_PATH="$GITHUB_WORKSPACE/$CONFIG/kernel_platform"
        MSM="$KERNEL_PATH/msm-kernel"
        cd "$MSM/drivers/net/wireless/realtek/"
        rm -rf rtw88
        git clone https://github.com/lwfinger/rtw88.git
        sed -i 's/$(CONFIG_RTW88)/m/g' Makefile
        sed -i '/^source "drivers\/net\/wireless\/realtek\/rtw88\/Kconfig"$/s/.*/ /' Kconfig

    - name: Detect Clang
      shell: bash
      run: |
        set -euo pipefail
        if command -v clang >/dev/null 2>&1; then
           echo "CLANG_BIN_PATH=$(dirname $(command -v clang))" >> "$GITHUB_ENV"
        else
           echo "Clang not found in path"
        fi

    - name: Build Kernel Modules
      shell: bash
      run: |
        set -euo pipefail
        KERNEL_PLATFORM="$GITHUB_WORKSPACE/$CONFIG/kernel_platform"
        MSM="$KERNEL_PLATFORM/msm-kernel"
        OUT=out
        export PATH="${CLANG_BIN_PATH}:$PATH" 
        export PATH="/usr/lib/ccache:$PATH"
        cd "$MSM"
        make ARCH=arm64 mrproper
        mkdir -p "$OUT"
        ./scripts/kconfig/merge_config.sh -O "$OUT" -m arch/arm64/configs/gki_defconfig arch/arm64/configs/vendor/${OP_SOC}_GKI.config
        
        echo "Building modules..."
        make ARCH=arm64 LLVM=1 O=out olddefconfig
        make -j$(nproc --all) ARCH=arm64 LLVM=1 O=out CC="ccache clang" modules
        
        INSTALL_MOD_PATH="$MSM/out/install"
        make -j$(nproc --all) ARCH=arm64 LLVM=1 O=out INSTALL_MOD_PATH=$INSTALL_MOD_PATH modules_install

    - name: Filter & Zip Modules
      id: create_zip
      shell: bash
      run: |
        set -euo pipefail
        MSM="$GITHUB_WORKSPACE/$CONFIG/kernel_platform/msm-kernel"
        INSTALL_PATH="$MSM/out/install"
        MODULES_DIR=$(find "$INSTALL_PATH" -type d -name "kernel" | head -n 1)
        mkdir -p "$GITHUB_WORKSPACE/$CONFIG/artifacts"
        ZIP_FILE="$GITHUB_WORKSPACE/$CONFIG/artifacts/kernel_modules.zip"
        cd "$MODULES_DIR"
        find . -type f -name "*.ko" -print0 | xargs -0 zip -j "$ZIP_FILE"
        echo "Modules Zipped ✅"

    - name: Upload Kernel Modules
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: Modules-Backup-Fixed
        path: ${{ env.CONFIG }}/artifacts/*.zip
