name: Build OnePlus kernel modules (Run 39 - Final)

permissions:
  contents: write
  actions: write

inputs:
  op_config_json:
    required: true
    type: string
  manifest:
    required: true
    type: string
    default: OOS15

runs:
  using: composite
  steps:
    - name: Free Disk Space (Nuclear Clean)
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo docker image prune --all --force
        sudo apt-get clean
        df -h

    - name: Parse op_config_json
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"
    
    - name: Set Manifest
      shell: bash
      run: |
        # Wahi Purana Logic jo Run 28 tak chala
        echo "OP_MANIFEST=$OP_MANIFEST_${{ inputs.manifest }}_MODULES" >> "$GITHUB_ENV"

    - name: Install Essential Dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          git curl ca-certificates build-essential clang lld flex bison \
          libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool \
          libxml2-utils rsync unzip dwarves file python3 ccache \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

    - name: Initialize and Sync Kernel Source
      shell: bash
      run: |
        set -euo pipefail
        CONFIG="$OP_MODEL"
        echo "CONFIG=$CONFIG" >> "$GITHUB_ENV"
        REPO="/usr/local/bin/repo"
        [ ! -x "$REPO" ] && curl -s https://storage.googleapis.com/git-repo-downloads/repo -o "$REPO" && chmod +x "$REPO"
        
        mkdir -p "$CONFIG" && cd "$CONFIG"
        
        # Manifest mapping (Strictly following your working pattern)
        MANIFEST_VAL="${!OP_MANIFEST}"
        
        "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b "$OP_BRANCH" -m "$MANIFEST_VAL" --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        "$REPO" sync -c -j$(nproc --all) --no-clone-bundle --no-tags --fail-fast

    - name: Add NetHunter Drivers (Ember's Fix)
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/kernel_platform/msm-kernel"
        
        # 1. RTL8188EU Injection (Ember's Suggestion)
        cd drivers/net/wireless/realtek/
        rm -rf rtw88 # Purana problematic driver hataya
        git clone --depth=1 https://github.com/ivanovborislav/rtl8188eu.git
        cd ../../../..
        
        # 2. Add Hacking Flags into gki_defconfig
        cat >> arch/arm64/configs/gki_defconfig <<EOF
        CONFIG_MODULES=y
        CONFIG_RTL8188EU=m
        CONFIG_TCP_CONG_BBR=m
        CONFIG_NETFILTER_XT_TARGET_TTL=m
        CONFIG_IP_SET=m
        CONFIG_FRAME_WARN=0
        EOF

    - name: Add MemKernel (Root)
      shell: bash
      run: |
        cd "$CONFIG/kernel_platform/msm-kernel"
        curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s M br0k3n

    - name: Build Kernel Modules (28min+ Goal)
      shell: bash
      run: |
        set -euo pipefail
        FIX_DIR="$GITHUB_WORKSPACE/$CONFIG/kernel_platform/msm-kernel"
        cd "$FIX_DIR"
        
        # Mandatory Patching (Jo tune Run 28 tak manually add kiye the)
        sed -i '1i #include <linux/mm.h>' drivers/thermal/thermal_sysfs.c
        find . -name kgdb.h -exec sed -i 's/asm ("brk %0"/\/\/ asm ("brk %0"/' {} +
        sed -i 's/scan_adjusted =/bool scan_adjusted =/' mm/vmscan.c

        # Setup Clang Path
        KP="$GITHUB_WORKSPACE/$CONFIG/kernel_platform"
        CLANG_BIN=$(ls -d "$KP"/prebuilts/clang/host/linux-x86/clang-r*/bin | tail -n1)
        export PATH="$CLANG_BIN:$PATH"

        OUT=out
        make ARCH=arm64 O=$OUT mrproper
        ./scripts/kconfig/merge_config.sh -O $OUT -m arch/arm64/configs/gki_defconfig arch/arm64/configs/vendor/${OP_SOC}_GKI.config
        
        # Linking Fix: Disable LTO (Crucial for CI)
        ./scripts/config --file "$OUT/.config" --disable CONFIG_LTO_CLANG_THIN --disable CONFIG_LTO_CLANG_FULL
        
        # Compilation with NO-ERROR Master Key
        make -j$(nproc --all) ARCH=arm64 LLVM=1 O=$OUT CC="ccache clang" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            KCFLAGS="-Wno-declaration-after-statement -Wno-unused-variable -Wno-macro-redefined -Wno-error" \
            modules
        
        # Collection
        mkdir -p artifacts
        find $OUT -name "*.ko" -exec cp {} artifacts/ \;
        cd artifacts && zip -r ../kernel_modules_final.zip .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jinn-modules-final
        path: ${{ env.CONFIG }}/kernel_platform/msm-kernel/kernel_modules_final.zip
        
