name: Build OnePlus kernel modules

permissions:
  contents: write
  actions: write

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true
    type: string
  optimize_level:
    required: false
    type: string
    default: O2  # Choices: O2 or O3
  manifest:
    required: true
    type: string
    default: OOS15

runs:
  using: composite
  steps:
    - name: Free Disk Space (Ubuntu)
      shell: bash
      run: |
        echo "::group::Freeing Disk Space"
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo docker image prune --all --force
        sudo apt-get clean
        df -h
        echo "::endgroup::"

    - name: Parse op_config_json
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"
        echo "Parsed config:"
        jq '.' /tmp/config.json
    
    - name: Set Manifest
      shell: bash
      run: |
        set -euo pipefail
        echo "OP_MANIFEST=$OP_MANIFEST_${{ inputs.manifest }}_MODULES" >> "$GITHUB_ENV"

    - name: Validate Inputs
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Validate inputs"
        model="$OP_MODEL"
        soc="$OP_SOC"
        branch="$OP_BRANCH"
        manifest="$OP_MANIFEST"
        optimize='${{ inputs.optimize_level }}'
        echo "Input validation OK."
        echo "::endgroup::"

    - name: Install Minimal Dependencies
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Install deps"
        sudo apt-get -o Acquire::Retries=3 update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          git curl ca-certificates build-essential clang lld flex bison \
          libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool \
          libxml2-utils rsync unzip dwarves file python3 ccache \
          gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
        sudo apt-get clean
        echo "::endgroup::"

    - name: Setup Base Environment
      shell: bash
      run: |
        set -euo pipefail
        CONFIG="$OP_MODEL"
        echo "CONFIG=$CONFIG" >> "$GITHUB_ENV"
        REPO="/usr/local/bin/repo"
        if [ ! -x "$REPO" ]; then
          curl -s https://storage.googleapis.com/git-repo-downloads/repo -o "$REPO"
          chmod +x "$REPO"
        fi
        echo "REPO=$REPO" >> "$GITHUB_ENV"

    - name: Initialize and Sync Kernel Source
      shell: bash
      run: |
        set -euo pipefail
        echo "Creating folder for configuration: $CONFIG"
        mkdir -p "$CONFIG"
        cd "$CONFIG"
        echo "Initializing and syncing kernel source..."
        if [[ "$OP_MANIFEST" == https://* ]]; then
          mkdir -p .repo/manifests
          curl --fail --show-error --location --proto '=https' "$OP_MANIFEST" -o .repo/manifests/temp_manifest.xml
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m temp_manifest.xml --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        else
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b "$OP_BRANCH" -m "$OP_MANIFEST" --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        fi
        "$REPO" --version
        success=false
        for i in 1 2 3; do
          if "$REPO" sync -c --no-clone-bundle --no-tags --optimized-fetch \
             -j"$(nproc --all)" --fail-fast; then
            success=true
            break
          fi
          echo "repo sync attempt $i failed; retrying..."
          sleep 30
        done
        $success || { echo "repo sync failed after 3 attempts"; exit 1; }

    - name: Get Kernel Version Info
      shell: bash
      run: |
        set -euo pipefail
        CONFIG_DIR="$GITHUB_WORKSPACE/$CONFIG"
        ARTIFACTS_DIR="$CONFIG_DIR/artifacts"
        mkdir -p "$ARTIFACTS_DIR"
        cd "$CONFIG_DIR/kernel_platform/msm-kernel"
        CONFIG_FILES=("build.config.common" "build.config.constants")
        BRANCH_LINE=""
        for f in "${CONFIG_FILES[@]}"; do
          if [ -f "$f" ]; then
            l=$(grep '^[[:space:]]*BRANCH=' "$f" || true)
            if [ -n "$l" ]; then BRANCH_LINE="$l"; break; fi
          fi
        done
        if [ -z "$BRANCH_LINE" ]; then echo "Error: No BRANCH= found"; exit 1; fi
        BRANCH_VALUE="${BRANCH_LINE#*=}"
        ANDROID_VERSION="${BRANCH_VALUE%-*}"
        VERSION=$(grep '^VERSION *=' Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep '^PATCHLEVEL *=' Makefile | awk '{print $3}')
        FULL_VERSION="$VERSION.$PATCHLEVEL"
        cd "$ARTIFACTS_DIR"
        echo "ANDROID_VER=$ANDROID_VERSION" >> "$GITHUB_ENV"
        echo "KERNEL_VER=$FULL_VERSION" >> "$GITHUB_ENV"
        echo "KERNEL_FULL_VER=$ANDROID_VERSION-$FULL_VERSION" >> "$GITHUB_ENV"

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.19
      with:
        key: ${{ env.CONFIG }}-modules-${{ env.KERNEL_FULL_VER }}
        max-size: 5G
        create-symlink: true

    - name: Clone kernel patches for msm kernel
      shell: bash
      run: |
        set -euo pipefail
        git clone --depth=1 https://github.com/nullptr-t-oss/kernel_patches.git my_patches

    - name: Clean Up ABI Protected Exports
      shell: bash
      run: |
        set -euo pipefail
        cd "$CONFIG/kernel_platform"
        rm -f msm-kernel/android/abi_gki_protected_exports_* || true

    - name: Add nethunter specfic drivers
      shell: bash
      run: |
        set -euo pipefail
        cd "$GITHUB_WORKSPACE/$CONFIG/kernel_platform/msm-kernel"
        cat >> arch/arm64/configs/gki_defconfig <<EOF
        CONFIG_WLAN_VENDOR_REALTEK=y
        CONFIG_WLAN_VENDOR_ATH=y
        CONFIG_ATH_COMMON=m
        CONFIG_ATH9K=m
        CONFIG_ATH9K_HW=m
        CONFIG_ATH9K_HTC=m
        CONFIG_ATH9K_COMMON=m
        CONFIG_ATH10K=m
        CONFIG_ATH10K_USB=m
        CONFIG_ATH11K=m
        CONFIG_WLAN_VENDOR_MEDIATEK=y
        CONFIG_MT7601U=m
        CONFIG_MT76_CORE=m
        CONFIG_MT76_USB=m
        CONFIG_MT76x02_LIB=m
        CONFIG_MT76x02_USB=m
        CONFIG_MT76_CONNAC_LIB=m
        CONFIG_MT7603E=m
        CONFIG_MT76x2_COMMON=m
        CONFIG_MT76x0_COMMON=m
        CONFIG_MT7615_COMMON=m
        CONFIG_MT7915E=m
        CONFIG_MT7921E=m
        CONFIG_MAC80211_LEDS=m
        CONFIG_CAN_SLCAN=m
        # --- WildKernelSU Features ---
        CONFIG_TCP_CONG_BBR=m
        CONFIG_NETFILTER_XT_TARGET_TTL=m
        CONFIG_NETFILTER_XT_MATCH_TTL=m
        CONFIG_NETFILTER_XT_TARGET_HL=m
        CONFIG_NETFILTER_XT_MATCH_HL=m
        CONFIG_IP_SET=m
        CONFIG_IP_SET_MAX=256
        CONFIG_IP_SET_BITMAP_IP=m
        CONFIG_IP_SET_BITMAP_IPMAC=m
        CONFIG_IP_SET_BITMAP_PORT=m
        CONFIG_IP_SET_HASH_IP=m
        CONFIG_IP_SET_HASH_IPMARK=m
        CONFIG_IP_SET_HASH_IPPORT=m
        CONFIG_IP_SET_HASH_IPPORTIP=m
        CONFIG_IP_SET_HASH_IPPORTNET=m
        CONFIG_IP_SET_HASH_IPMAC=m
        CONFIG_IP_SET_HASH_MAC=m
        CONFIG_IP_SET_HASH_NETPORTNET=m
        CONFIG_IP_SET_HASH_NET=m
        CONFIG_IP_SET_HASH_NETNET=m
        CONFIG_IP_SET_HASH_NETPORT=m
        CONFIG_IP_SET_HASH_NETIFACE=m
        CONFIG_IP_SET_LIST_SET=m
        
        # --- CONFIG FIXES ---
        CONFIG_FRAME_WARN=0
        # --------------------
        EOF

    - name: Add memkernel module
      shell: bash
      run: |
        set -euo pipefail
        cd "$GITHUB_WORKSPACE/$CONFIG/kernel_platform/msm-kernel"
        curl -LSs "https://raw.githubusercontent.com/Poko-Apps/MemKernel/main/kernel/setup.sh" | bash -s M br0k3n

    - name: Add rtw88 modules
      shell: bash
      run: |
        set -euo pipefail
        cd "$GITHUB_WORKSPACE/$CONFIG/kernel_platform/msm-kernel/drivers/net/wireless/realtek/"
        rm -rf rtw88
        git clone https://github.com/lwfinger/rtw88.git
        sed -i 's/$(CONFIG_RTW88)/m/g' Makefile
        sed -i '/^source "drivers\/net\/wireless\/realtek\/rtw88\/Kconfig"$/s/.*/ /' Kconfig

    - name: Detect Clang
      shell: bash
      run: |
        set -euo pipefail
        KP="$GITHUB_WORKSPACE/$CONFIG/kernel_platform"
        CLANG_FOUND=false
        for base in "$KP/prebuilts" "$KP/prebuilts-master"; do
          [ -d "$base/clang/host/linux-x86" ] || continue
          latest=$(ls -d "$base"/clang/host/linux-x86/clang-r*/ 2>/dev/null | sort -V | tail -n1 || true)
          if [ -n "$latest" ] && [ -x "$latest/bin/clang" ]; then
            CLANG_BIN="$latest/bin"
            CLANG_FOUND=true
            fi
        done
        if ! $CLANG_FOUND && command -v clang >/dev/null 2>&1; then
          CLANG_BIN="$(dirname "$(command -v clang)")"
          CLANG_FOUND=true
        fi
        $CLANG_FOUND || { echo "No clang toolchain found"; exit 1; }
        echo "CLANG_BIN_PATH=$CLANG_BIN" >> "$GITHUB_ENV"

    - name: Build Kernel Modules 
      shell: bash
      run: |
        set -euo pipefail
        
        # --- NUCLEAR FIX START ---
        echo ">>> APPLYING MANDATORY FIXES..."
        FIX_DIR="$GITHUB_WORKSPACE/$CONFIG/kernel_platform/msm-kernel"
        cd "$FIX_DIR"
        
        # FIX 1: stack_pointer.h - NO EDIT (LTO disabled handles this)
        echo "Skipping stack_pointer.h edits (Relying on disabling LTO)..."
        
        # FIX 2: kgdb.h (Break error fix)
        echo "Fixing kgdb.h..."
        find . -name kgdb.h -exec sed -i 's/asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/\/\/ asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/' {} +
        
        # FIX 3: vmscan.c (Injecting variable declaration)
        echo "Fixing vmscan.c missing variable..."
        sed -i 's/scan_adjusted = (!cgroup_reclaim/bool scan_adjusted = (!cgroup_reclaim/' mm/vmscan.c
        
        # FIX 4: thermal_sysfs.c (Missing header for kvzalloc)
        echo "Fixing thermal_sysfs.c missing header..."
        sed -i '1i #include <linux/mm.h>' drivers/thermal/thermal_sysfs.c
        
        echo ">>> FIXES APPLIED SUCCESSFULLY!"
        # --- NUCLEAR FIX END ---

        KERNEL_PLATFORM="$GITHUB_WORKSPACE/$CONFIG/kernel_platform"
        MSM="$KERNEL_PLATFORM/msm-kernel"
        OUT=out

        export PATH="${CLANG_BIN_PATH}:$PATH" 
        export PATH="/usr/lib/ccache:$PATH"

        cd "$MSM"

        make ARCH=arm64 mrproper
        mkdir -p "$OUT"

        ./scripts/kconfig/merge_config.sh -O "$OUT" -m arch/arm64/configs/gki_defconfig arch/arm64/configs/vendor/${OP_SOC}_GKI.config

        # --- DISABLE LTO ---
        ./scripts/config --file "$OUT/.config" \
            --disable CONFIG_LTO \
            --disable CONFIG_LTO_CLANG \
            --disable CONFIG_LTO_CLANG_THIN \
            --disable CONFIG_LTO_CLANG_FULL \
            --disable CONFIG_THINLTO \
            --enable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE \
            --disable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3

        INSTALL_MOD_PATH="$MSM/out"

        echo "Building kernel modules..."
        make ARCH=arm64 LLVM=1 O=out olddefconfig
        
        # ADDED KCFLAGS TO IGNORE C90 AND UNUSED VAR ERRORS
        make -j$(nproc --all) ARCH=arm64 LLVM=1 O=out CC="ccache clang" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
            KCFLAGS="-Wno-declaration-after-statement -Wno-unused-variable" \
            modules        
        
        make -j$(nproc --all) ARCH=arm64 LLVM=1 O=out INSTALL_MOD_PATH=$INSTALL_MOD_PATH modules_install

    - name: Filter modules
      shell: bash
      run: |
        set -euo pipefail
        KERNEL_PLATFORM="$GITHUB_WORKSPACE/$CONFIG/kernel_platform"
        MSM="$KERNEL_PLATFORM/msm-kernel"
        OUT="$MSM/out"
        UNAME=$(ls "$OUT/lib/modules/")
        echo "Copying all modules to $OUT/modules"
        cd "$OUT"
        mkdir -p modules
        find lib/modules/"$UNAME" -type f -name '*.ko' -exec cp {} modules/ \;
        cd modules
        curl -L -o default_modules.txt https://raw.githubusercontent.com/nullptr-t-oss/kernel_patches/refs/heads/main/default_modules.txt
        while IFS= read -r module; do
          if [ -e "$module" ]; then
            rm -f "$module"
          fi
        done < default_modules.txt

    - name: Create Kernel Modules zip
      id: create_zip
      shell: bash
      run: |
        set -euo pipefail
        CONFIG_DIR="$GITHUB_WORKSPACE/$CONFIG"
        MSM="$CONFIG_DIR/kernel_platform/msm-kernel"
        OUT="$MSM/out"
        MODULES_SRC="$OUT/modules"
        MODULES_ZIP="$CONFIG_DIR/artifacts/kernel_modules_${{ env.OP_MODEL }}.zip"
        mkdir -p "$CONFIG_DIR/artifacts"
        find "$MODULES_SRC" -type f -name '*.ko' -print0 | xargs -0 zip -j "$MODULES_ZIP"

    - name: Final Build Summary
      shell: bash
      run: |
        set -euo pipefail
        echo "### Kernel Modules Build Summary" >> "$GITHUB_STEP_SUMMARY"
        echo "$(ccache -s -v)" >> "$GITHUB_STEP_SUMMARY"

    - name: Cleanup old ccache
      shell: bash
      run: |
        set -euo pipefail
        gh cache delete ccache-${{ env.CONFIG }}-modules-${{ env.KERNEL_FULL_VER }}- || true

    - name: Upload Kernel Modules zip
      if: success() && steps.create_zip.conclusion == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: kernel-modules-${{ env.CONFIG }}
        path: ${{ env.CONFIG }}/artifacts/
        
