    - name: Build Kernel Modules (Final Path Fix)
      shell: bash
      run: |
        set -euo pipefail
        # 1. Sabse pehle compiler dhoondte hain
        echo "Searching for Clang in all prebuilts..."
        CLANG_BIN=$(find $GITHUB_WORKSPACE/$CONFIG/kernel_platform -name clang -type f -path "*/bin/clang" | head -n 1 | xargs dirname || echo "")
        
        if [ -z "$CLANG_BIN" ]; then
          echo "ERROR: Clang not found in synced source!"
          # Fallback to system clang if source one is missing
          CLANG_BIN="/usr/bin"
        fi
        
        echo "Compiler found at: $CLANG_BIN"
        export PATH="$CLANG_BIN:$PATH"

        # 2. Build process shuru karte hain
        cd "$GITHUB_WORKSPACE/$CONFIG/kernel_platform/msm-kernel"
        
        # Mandatory Patching (Run 28 fixes)
        sed -i '1i #include <linux/mm.h>' drivers/thermal/thermal_sysfs.c
        find . -name kgdb.h -exec sed -i 's/asm ("brk %0"/\/\/ asm ("brk %0"/' {} +
        sed -i 's/scan_adjusted =/bool scan_adjusted =/' mm/vmscan.c

        OUT=out
        make ARCH=arm64 O=$OUT LLVM=1 mrproper
        
        # GKI Config Merge
        ./scripts/kconfig/merge_config.sh -O $OUT -m arch/arm64/configs/gki_defconfig arch/arm64/configs/vendor/${OP_SOC}_GKI.config
        
        # Disable LTO (Linking phase fix)
        ./scripts/config --file "$OUT/.config" --disable CONFIG_LTO_CLANG_THIN --disable CONFIG_LTO_CLANG_FULL
        
        # Build with Master Bypass Flags
        make -j$(nproc --all) ARCH=arm64 LLVM=1 O=$OUT \
            KCFLAGS="-Wno-error -Wno-macro-redefined -Wno-declaration-after-statement -Wno-unused-variable" \
            modules

        # Zip artifacts
        mkdir -p artifacts
        find $OUT -name "*.ko" -exec cp {} artifacts/ \;
        cd artifacts && zip -r ../kernel_modules_final.zip .
        
