name: Build OnePlus EmberHeart Kernel (Clean & Fixed)
description: 'Final Manual Build - No Excess Patches'

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true

runs:
  using: composite
  steps:
    - name: ⚙️ Setup Environment
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"
        echo "OP_MANIFEST=oneplus_10_pro_v.xml" >> "$GITHUB_ENV"
        echo "CONFIG=OP10-Pro" >> "$GITHUB_ENV"
        echo "WORKSPACE_DIR=${{ github.workspace }}/workspace" >> "$GITHUB_ENV"

    - name: 📦 Install Dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y git curl build-essential clang lld llvm flex bison \
        libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool libxml2-utils \
        rsync unzip dwarves file python3 ccache python3-pip \
        gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

        # Repo Tool
        sudo curl -s https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod +x /usr/local/bin/repo

    - name: 🔄 Sync FULL Source
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p ${{ env.WORKSPACE_DIR }}
        cd ${{ env.WORKSPACE_DIR }}
        
        echo "::group::Syncing via Manifest..."
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8450 -m ${{ env.OP_MANIFEST }} --depth=1
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        echo "::endgroup::"

    - name: 🛠️ Apply ONLY Necessary Fixes
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel
        
        echo "::group::Applying Patches..."
        
        # 1. Thermal Fix (Ye 100% zaroori hai)
        if [ -f "drivers/thermal/thermal_sysfs.c" ]; then
             sed -i '1i #include <linux/mm.h>' "drivers/thermal/thermal_sysfs.c"
             echo "✅ Fixed thermal_sysfs.c"
        fi
        
        # 2. KGDB Fix (Safe to keep)
        if [ -f "arch/arm64/include/asm/kgdb.h" ]; then
             sed -i 's/asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/\/\/ asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/' "arch/arm64/include/asm/kgdb.h"
             echo "✅ Fixed kgdb.h"
        fi

        # 3. CPUSET Fix (Jo pichli baar aya tha)
        # Hum missing header add kar rahe hain taaki 'cpuset_cgrp_id' error na aaye
        if [ -f "kernel/sched/core.c" ]; then
             sed -i '1i #include <linux/cpuset.h>' "kernel/sched/core.c"
             echo "✅ Fixed sched/core.c (Added cpuset.h)"
        fi
        
        # NOTE: Stack Pointer fix HATA DIYA hai kyunki CLANG_TRIPLE usse khud sambhal lega.
        echo "::endgroup::"

    - name: 🔥 Build Kernel (Clean Build)
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel
        
        echo "::group::Configuring..."
        mkdir -p out
        # Merge Configs
        ./scripts/kconfig/merge_config.sh -O out arch/arm64/configs/gki_defconfig arch/arm64/configs/vendor/waipio_GKI.config
        
        # Inject NetHunter & Ensure CPUSETS is ON
        cat >> out/.config <<EOF
        CONFIG_USB_CONFIGFS_F_HID=y
        CONFIG_USB_CONFIGFS_F_ACC=y
        CONFIG_USB_CONFIGFS_UEVENT=y
        CONFIG_USB_SERIAL=y
        CONFIG_USB_SERIAL_CH341=y
        CONFIG_R8188EU=y
        CONFIG_RTL8188EU=y
        CONFIG_IP_SET=y
        CONFIG_TCP_CONG_BBR=y
        CONFIG_CPUSETS=y
        CONFIG_LOCALVERSION="-NetHunter-Jinn"
        EOF
        
        make ARCH=arm64 O=out olddefconfig
        echo "::endgroup::"

        echo "::group::🚀 Compiling Image..."
        make -j$(nproc --all) \
             ARCH=arm64 \
             LLVM=1 \
             LLVM_IAS=1 \
             O=out \
             CLANG_TRIPLE=aarch64-linux-gnu- \
             CROSS_COMPILE=aarch64-linux-gnu- \
             CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
             LD=ld.lld \
             CC="ccache clang" \
             Image
        echo "::endgroup::"

    - name: 📦 Collect Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Jinn-NetHunter-Success
        path: |
          ${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel/out/arch/arm64/boot/Image
          ${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel/out/**/boot.img
          
