name: Build OnePlus EmberHeart Kernel (The Real Fix)
description: 'Full Repo Sync to fix missing drivers'

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true

runs:
  using: composite
  steps:
    - name: âš™ï¸ Setup Environment
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"
        echo "OP_MANIFEST=oneplus_10_pro_v.xml" >> "$GITHUB_ENV"
        echo "CONFIG=OP10-Pro" >> "$GITHUB_ENV"
        # Workspace define kar rahe hain taaki repo sync sahi jagah ho
        echo "WORKSPACE_DIR=${{ github.workspace }}/workspace" >> "$GITHUB_ENV"

    - name: ðŸ“¦ Install Dependencies & Repo Tool
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y git curl build-essential clang lld flex bison \
        libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool libxml2-utils \
        rsync unzip dwarves file python3 ccache python3-pip

        # Google ka official Repo tool install karna zaroori hai
        sudo curl -s https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod +x /usr/local/bin/repo

    - name: ðŸ”„ Sync FULL Source (Fixing Missing Drivers)
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p ${{ env.WORKSPACE_DIR }}
        cd ${{ env.WORKSPACE_DIR }}
        
        echo "::group::Syncing via Manifest..."
        # Fatalcoder wala command, lekin humare environment variables ke saath
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8450 -m ${{ env.OP_MANIFEST }} --depth=1
        
        # 'force-sync' zaroori hai taaki purana kachra saaf ho jaye
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        echo "::endgroup::"

    - name: ðŸ’‰ Inject NetHunter (Built-in Mode)
      shell: bash
      run: |
        set -euo pipefail
        # Ab hum sahi folder structure mein ja rahe hain
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform
        
        echo "::group::Injecting Configs..."
        find common/arch/arm64/configs -name "gki_defconfig" -o -name "waipio_GKI.config" | while read config_file; do
          echo "Patching: $config_file"
          cat >> "$config_file" <<EOF
        # Jinn NetHunter Configs (Built-in Force)
        CONFIG_USB_CONFIGFS_F_HID=y
        CONFIG_USB_CONFIGFS_F_ACC=y
        CONFIG_USB_CONFIGFS_UEVENT=y
        CONFIG_USB_SERIAL=y
        CONFIG_USB_SERIAL_CH341=y
        CONFIG_R8188EU=y
        CONFIG_RTL8188EU=y
        CONFIG_IP_SET=y
        CONFIG_TCP_CONG_BBR=y
        CONFIG_LOCALVERSION="-NetHunter-Jinn"
        EOF
        done
        
        # Thermal error fix jo pichli baar aaya tha
        THERMAL_FILE="msm-kernel/drivers/thermal/thermal_sysfs.c"
        if [ -f "$THERMAL_FILE" ]; then
             sed -i '1i #include <linux/mm.h>' "$THERMAL_FILE"
        fi
        echo "::endgroup::"

    - name: ðŸ”¥ Build Kernel (Official Script)
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform
        
        # OnePlus ka official build command use kar rahe hain
        ./build/build.sh -c waipio_gki -t waipio_gki -a arm64 -v 5.10
        
        echo "Build Complete âœ…"

    - name: ðŸ“¦ Collect Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Jinn-NetHunter-Final
        path: |
          ${{ env.WORKSPACE_DIR }}/out/**/Image
          ${{ env.WORKSPACE_DIR }}/out/**/boot.img
