name: Build OnePlus EmberHeart Kernel

permissions:
  contents: write
  actions: write

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true
    type: string
  ksun_branch_or_hash:
    required: true
    type: string
    default: ""
  susfs_commit_hash_or_branch:
    required: false
    type: string
    default: "dev"
  optimize_level:
    required: false
    type: string
    default: O2
  kernel_uname:
    required: false
    type: string
    default: "EmberHeart"
  manifest:
    required: true
    type: string
    default: OOS15

runs:
  using: composite
  steps:
    - name: Parse op_config_json
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"
        jq '.' /tmp/config.json

    - name: Set Manifest
      shell: bash
      run: |
        set -euo pipefail
        echo "OP_MANIFEST=$OP_MANIFEST_${{ inputs.manifest }}" >> "$GITHUB_ENV"

    - name: Install Minimal Dependencies
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update -qq
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          git curl ca-certificates build-essential clang lld flex bison \
          libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool \
          libxml2-utils rsync unzip dwarves file python3 ccache
        sudo apt-get clean

    - name: Setup Base Environment
      shell: bash
      run: |
        set -euo pipefail
        echo "CONFIG=$OP_MODEL" >> "$GITHUB_ENV"
        REPO="/usr/local/bin/repo"
        if [ ! -x "$REPO" ]; then
          curl -s https://storage.googleapis.com/git-repo-downloads/repo -o "$REPO"
          chmod +x "$REPO"
        fi
        echo "REPO=$REPO" >> "$GITHUB_ENV"

    - name: Initialize and Sync Kernel Source
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "$CONFIG"
        cd "$CONFIG"
        if [[ "$OP_MANIFEST" == https://* ]]; then
          mkdir -p .repo/manifests
          curl --fail --show-error --location "$OP_MANIFEST" -o .repo/manifests/temp_manifest.xml
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m temp_manifest.xml --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        else
          "$REPO" init -u https://github.com/OnePlusOSS/kernel_manifest.git -b "$OP_BRANCH" -m "$OP_MANIFEST" --repo-rev=v2.16 --depth=1 --no-clone-bundle --no-tags
        fi
        "$REPO" sync -c --no-clone-bundle --no-tags --optimized-fetch -j"$(nproc --all)" --fail-fast

    - name: 💉 Inject NetHunter, RTL8188EU & Network Configs
      shell: bash
      run: |
        set -euo pipefail
        echo "::group::Applying NetHunter Injection..."
        # Sahi path par jana jahan gki_defconfig hoti hai
        cd "$CONFIG/kernel_platform/common"
        
        # Sabhi possible configs me inject karo
        find arch/arm64/configs -name "*defconfig" -o -name "*.config" | while read config_file; do
          echo "Patching: $config_file"
          cat >> "$config_file" <<EOF

        # --- Jinn NetHunter Injection ---
        CONFIG_USB_CONFIGFS_F_HID=y
        CONFIG_USB_CONFIGFS_F_ACC=y
        CONFIG_USB_CONFIGFS_UEVENT=y
        CONFIG_MAC80211=y
        CONFIG_MAC80211_LEDS=y
        CONFIG_MAC80211_MESH=y
        CONFIG_CDROM=y
        CONFIG_USB_SERIAL=y
        CONFIG_USB_SERIAL_CH341=y
        CONFIG_USB_SERIAL_FTDI_SIO=y
        CONFIG_USB_SERIAL_PL2303=y

        # --- RTL8188EU Driver ---
        CONFIG_STAGING=y
        CONFIG_R8188EU=y
        CONFIG_RTL8188EU=y

        # --- Network Support ---
        CONFIG_IP_SET=y
        CONFIG_IP_SET_MAX=65534
        CONFIG_IP_SET_HASH_IP=y
        CONFIG_IP_SET_HASH_NET=y
        CONFIG_IP_SET_LIST_SET=y
        CONFIG_IP_NF_TARGET_TTL=y
        CONFIG_IP6_NF_TARGET_HL=y
        CONFIG_IP6_NF_MATCH_HL=y
        CONFIG_LOCALVERSION="-NetHunter-Jinn"
        EOF
        done
        echo "Injection Complete ✅"
        echo "::endgroup::"

    - name: Build Kernel (Original Action)
      # Yahan se aage ka code tumhare original system ka hai taaki build pass ho
      shell: bash
      run: |
        # Yahan tumhara build script chalao jo pehle tha
        echo "Starting build..."
        # ... (Build commands)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-${{ env.CONFIG }}
        path: ${{ env.CONFIG }}/artifacts/
        
