- name: 🔥 Build Kernel (Fixed Config Path)
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform
        
        echo "::group::Fixing Missing Config..."
        # Error yahan tha: Script 'build.config' dhoondh raha tha par wo 'common' folder me tha
        # Hum us file ko dhoondh kar bahar link kar rahe hain
        if [ -f "common/build.config.gki.aarch64" ]; then
            ln -sf common/build.config.gki.aarch64 build.config
            echo "Linked build.config.gki.aarch64 ✅"
        elif [ -f "common/build.config" ]; then
            ln -sf common/build.config build.config
            echo "Linked common/build.config ✅"
        else
            # Agar common me na mile toh msm-kernel me check karo
            ln -sf msm-kernel/build.config build.config
            echo "Linked msm-kernel/build.config ✅"
        fi
        echo "::endgroup::"

        echo "::group::Starting Build..."
        # Ab script ko build.config mil jayega
        # BUILD_CONFIG variable bhi set kar dete hain safety ke liye
        export BUILD_CONFIG=build.config
        
        ./build/build.sh -c waipio_gki -t waipio_gki -a arm64 -v 5.10
        echo "::endgroup::"
