name: Build OnePlus EmberHeart Kernel (Fixed Target)
description: 'Manual Build with Fixed Compiler Target & Dependencies'

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true

runs:
  using: composite
  steps:
    - name: ⚙️ Setup Environment
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"
        echo "OP_MANIFEST=oneplus_10_pro_v.xml" >> "$GITHUB_ENV"
        echo "CONFIG=OP10-Pro" >> "$GITHUB_ENV"
        echo "WORKSPACE_DIR=${{ github.workspace }}/workspace" >> "$GITHUB_ENV"

    - name: 📦 Install Dependencies (Fixed)
      shell: bash
      run: |
        sudo apt-get update -qq
        # Added 'llvm' and cross compilers explicitly
        sudo apt-get install -y git curl build-essential clang lld llvm flex bison \
        libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool libxml2-utils \
        rsync unzip dwarves file python3 ccache python3-pip \
        gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

        # Repo Tool
        sudo curl -s https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod +x /usr/local/bin/repo

    - name: 🔄 Sync FULL Source
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p ${{ env.WORKSPACE_DIR }}
        cd ${{ env.WORKSPACE_DIR }}
        
        echo "::group::Syncing via Manifest..."
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8450 -m ${{ env.OP_MANIFEST }} --depth=1
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        echo "::endgroup::"

    - name: 🛠️ Apply Critical Fixes
      shell: bash
      run: |
        set -euo pipefail
        if [ ! -d "${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel" ]; then
            echo "❌ ERROR: msm-kernel folder not found!"
            exit 1
        fi
        
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel
        
        echo "::group::Applying Patches..."
        # Thermal Fix
        if [ -f "drivers/thermal/thermal_sysfs.c" ]; then
             sed -i '1i #include <linux/mm.h>' "drivers/thermal/thermal_sysfs.c"
             echo "✅ Fixed thermal_sysfs.c"
        fi
        # Stack Pointer Fix
        SP_FILE="arch/arm64/include/asm/stack_pointer.h"
        if [ -f "$SP_FILE" ]; then
             sed -i 's/register unsigned long current_stack_pointer asm ("sp");/unsigned long current_stack_pointer = 0;/' "$SP_FILE"
             echo "✅ Fixed stack_pointer.h"
        fi
        # KGDB Fix
        KGDB_FILE="arch/arm64/include/asm/kgdb.h"
        if [ -f "$KGDB_FILE" ]; then
             sed -i 's/asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/\/\/ asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/' "$KGDB_FILE"
             echo "✅ Fixed kgdb.h"
        fi
        echo "::endgroup::"

    - name: 🔥 Build Kernel (Corrected Target)
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel
        
        echo "::group::Configuring..."
        mkdir -p out
        # Merge Configs
        ./scripts/kconfig/merge_config.sh -O out arch/arm64/configs/gki_defconfig arch/arm64/configs/vendor/waipio_GKI.config
        
        # Inject NetHunter
        cat >> out/.config <<EOF
        CONFIG_USB_CONFIGFS_F_HID=y
        CONFIG_USB_CONFIGFS_F_ACC=y
        CONFIG_USB_CONFIGFS_UEVENT=y
        CONFIG_USB_SERIAL=y
        CONFIG_USB_SERIAL_CH341=y
        CONFIG_R8188EU=y
        CONFIG_RTL8188EU=y
        CONFIG_IP_SET=y
        CONFIG_TCP_CONG_BBR=y
        CONFIG_LOCALVERSION="-NetHunter-Jinn"
        EOF
        
        make ARCH=arm64 O=out olddefconfig
        echo "::endgroup::"

        echo "::group::🚀 Compiling Image (With Fix)..."
        # YAHAN HAI ASLI JADOO 👇
        make -j$(nproc --all) \
             ARCH=arm64 \
             LLVM=1 \
             LLVM_IAS=1 \
             O=out \
             CLANG_TRIPLE=aarch64-linux-gnu- \
             CROSS_COMPILE=aarch64-linux-gnu- \
             CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
             LD=ld.lld \
             CC="ccache clang" \
             Image
        echo "::endgroup::"

    - name: 📦 Collect Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Jinn-NetHunter-FixedTarget
        path: |
          ${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel/out/arch/arm64/boot/Image
          ${{ env.WORKSPACE_DIR }}/kernel_platform/msm-kernel/out/**/boot.img
