name: Build OnePlus EmberHeart Kernel (Auto-Fix Config)
description: 'Full Repo Sync with Auto-Discovery of Build Config'

inputs:
  op_config_json:
    description: 'JSON string containing full device config'
    required: true

runs:
  using: composite
  steps:
    - name: ⚙️ Setup Environment
      shell: bash
      run: |
        set -euo pipefail
        echo '${{ inputs.op_config_json }}' > /tmp/config.json
        jq -r 'to_entries[] | "OP_\(.key | ascii_upcase)=\(.value)"' /tmp/config.json >> "$GITHUB_ENV"
        echo "OP_MANIFEST=oneplus_10_pro_v.xml" >> "$GITHUB_ENV"
        echo "CONFIG=OP10-Pro" >> "$GITHUB_ENV"
        echo "WORKSPACE_DIR=${{ github.workspace }}/workspace" >> "$GITHUB_ENV"

    - name: 📦 Install Dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y git curl build-essential clang lld flex bison \
        libelf-dev libssl-dev libncurses-dev zlib1g-dev liblz4-tool libxml2-utils \
        rsync unzip dwarves file python3 ccache python3-pip

        # Repo Tool
        sudo curl -s https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod +x /usr/local/bin/repo

    - name: 🔄 Sync FULL Source
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p ${{ env.WORKSPACE_DIR }}
        cd ${{ env.WORKSPACE_DIR }}
        
        echo "::group::Syncing via Manifest..."
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8450 -m ${{ env.OP_MANIFEST }} --depth=1
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
        echo "::endgroup::"

    - name: 💉 Inject NetHunter & Fixes
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform
        
        echo "::group::Injecting Configs..."
        find common/arch/arm64/configs -name "gki_defconfig" -o -name "waipio_GKI.config" | while read config_file; do
          echo "Patching: $config_file"
          cat >> "$config_file" <<EOF
        CONFIG_USB_CONFIGFS_F_HID=y
        CONFIG_USB_CONFIGFS_F_ACC=y
        CONFIG_USB_CONFIGFS_UEVENT=y
        CONFIG_USB_SERIAL=y
        CONFIG_USB_SERIAL_CH341=y
        CONFIG_R8188EU=y
        CONFIG_RTL8188EU=y
        CONFIG_IP_SET=y
        CONFIG_TCP_CONG_BBR=y
        CONFIG_LOCALVERSION="-NetHunter-Jinn"
        EOF
        done

        # CRITICAL COMPILER FIXES
        MSM_DIR="msm-kernel"
        # 1. Thermal Fix
        if [ -f "$MSM_DIR/drivers/thermal/thermal_sysfs.c" ]; then
             sed -i '1i #include <linux/mm.h>' "$MSM_DIR/drivers/thermal/thermal_sysfs.c"
        fi
        # 2. Stack Pointer Fix
        SP_FILE="$MSM_DIR/arch/arm64/include/asm/stack_pointer.h"
        if [ -f "$SP_FILE" ]; then
             sed -i 's/register unsigned long current_stack_pointer asm ("sp");/unsigned long current_stack_pointer = 0;/' "$SP_FILE"
        fi
        # 3. KGDB Fix
        KGDB_FILE="$MSM_DIR/arch/arm64/include/asm/kgdb.h"
        if [ -f "$KGDB_FILE" ]; then
             sed -i 's/asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/\/\/ asm ("brk %0" : : "I" (KGDB_COMPILED_DBG_BRK_IMM));/' "$KGDB_FILE"
        fi
        echo "::endgroup::"

    - name: 🔥 Build Kernel (Auto-Find Config)
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ env.WORKSPACE_DIR }}/kernel_platform
        
        echo "::group::🔍 DEBUG: File Structure"
        ls -F
        echo "--------------------------------"
        echo "::endgroup::"

        echo "::group::🚀 Setting up Build Config..."
        # Forcefully find the GKI config and copy it to root as 'build.config'
        # Hum file ko dhoondh kar zabardasti root par copy kar rahe hain
        echo "Searching for build.config.gki.aarch64..."
        find . -name "build.config.gki.aarch64" -exec cp -v {} build.config \; -print -quit
        
        # Check if copy worked
        if [ -f "build.config" ]; then
            echo "✅ FOUND IT! build.config created successfully."
        else
            echo "⚠️ GKI config not found, searching for ANY build.config..."
            find . -name "build.config.msm.waipio" -exec cp -v {} build.config \; -print -quit
        fi

        # Final check
        if [ ! -f "build.config" ]; then
            echo "❌ CRITICAL ERROR: Could not find any build config file!"
            echo "Listing all build files for debugging:"
            find . -name "build.config*"
            exit 1
        fi
        echo "::endgroup::"

        echo "::group::🔥 Starting Build Script..."
        export BUILD_CONFIG=build.config
        ./build/build.sh -c waipio_gki -t waipio_gki -a arm64 -v 5.10
        echo "::endgroup::"

    - name: 📦 Collect Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Jinn-NetHunter-Final
        path: |
          ${{ env.WORKSPACE_DIR }}/out/**/Image
          ${{ env.WORKSPACE_DIR }}/out/**/boot.img
